"use client";
import { useTranslations } from "next-intl";
import { handleApiError } from "@/lib/utils/handleApiError";
import CreatePage from "@/components/dashboard/CreatePage";
import { useCreateExpenseCategoryMutation } from "@/redux/services/dashboard/purchase/expenseCategory";
import ExpenseCategoryForm, {
  ExpenseCategoryFormValues,
} from "@/components/dashboard/forms/purchase/PurchaseExpenseCategoryForm";
// import ExpenseCategoryForm, { ExpenseCategoryFormValues } from "@/components/dashboard/forms/purchase/ExpenseCategoryForm";

export default function CreateExpenseCategory() {
  const t = useTranslations("Purchase.ExpenseCategory");
  const [createExpenseCategory, { isLoading }] =
    useCreateExpenseCategoryMutation();

  const handleSubmit = async (data: ExpenseCategoryFormValues) => {
    // Simple payload that matches your API structure
    const payload = {
      name: data.name,
      description: data.description || "", // Optional field
      // id is auto-generated by backend for creation, don't include it
    };

    const response = await createExpenseCategory(payload);

    if ("error" in response) {
      // Handle API error
      handleApiError(response.error);
    }
  };

  return (
    <CreatePage
      title={t("addExpenseCategory")}
      onSubmit={handleSubmit}
      Form={ExpenseCategoryForm}
      redirectPath="/dashboard/purchase?tab=expenseCategory" // Fixed redirect path
      isLoading={isLoading}
    />
  );
}
