// Define permission requirements for specific routes
export const permissionRoutes = {
  "/dashboard/inventory": [
    "unit",
    "inventoryitem",
    "expensecategory",
    "preorder",
    "movement",
    "stockadjustment",
  ],
  "/dashboard/sales": [
    "salesinvoice",
    "customer",
    "quotation",
    "order",
    "invoice",
    "clientrequest",
    "followup",
  ],
  "/dashboard/hr": [
    "employee",
    "department",
    "attendance",
    "leaverequest",
    "bonusdeduction",
    "applicant",
    "interview",
    "competition",
    "evaluation",
    "jobrole",
  ],
  "/dashboard/clients": ["customer"],
  "/dashboard/branches": ["branch", "branchaccounttransaction"],
  "/dashboard/website": [
    "service",
    "gallery",
    "contact",
    "customerreview",
    "socialcode",
    "blog",
  ],
  "/dashboard/purchase": [
    "expensecategory",
    "invoicedetail",
    "purchaseorder",
    "purchaserequest",
    "supplier",
    "warehouse",
  ],
   "/dashboard/finance": ["customer"],
   "/dashboard/analytics": ["analytics"],
   "/dashboard/reports": ["reports"],
};
